# Generated by Django 3.1.7 on 2023-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('sns_img', models.ImageField(upload_to='')),
                ('good_num', models.IntegerField()),
                ('read_text', models.TextField()),
            ],
        ),
    ]
