# Generated by Django 3.1.7 on 2023-11-26 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board_model',
            old_name='good_num',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='board_model',
            old_name='sns_img',
            new_name='snsimg',
        ),
        migrations.AddField(
            model_name='board_model',
            name='read',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
