# Generated by Django 3.1.7 on 2023-12-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board_model',
            old_name='sns_img',
            new_name='snsimg',
        ),
        migrations.RemoveField(
            model_name='board_model',
            name='good_num',
        ),
        migrations.AddField(
            model_name='board_model',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board_model',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
