# Generated by Django 3.1.7 on 2024-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20231208_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_model',
            name='snsimg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
